
"""
Django settings for insecom project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _
from celery.schedules import crontab
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x6oj9vvh#$(u^82qkaxjp%zjck@93$gd!zh+&pkx(mu-_a-*w)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.core',
    'apps.users',
    'ckeditor',
    'ckeditor_uploader',
    'apps.personalhealth',
    'apps.payment',
    'apps.about',
    'apps.article',
    'apps.cancel',
    'apps.claim',
    'apps.corporatehealth',
    'apps.critical',
    'apps.deal',
    'apps.delay',
    'apps.education',
    'apps.homeinsurance',
    'apps.hospitalcash',
    'apps.investment',
    'apps.kienthuc',
    'apps.mobilescreen',
    'apps.pension',
    'apps.personalaccident',
    'apps.renewal',
    'apps.robot',
    'apps.saving',
    'apps.termlife',
    'apps.tndsoto',
    'apps.tndsxemay',
    'apps.travelquocte',
    'apps.travelvn',
    'apps.vatchatxeoto',
    'apps.bhhocsinh',
    'apps.insurancecompany',

    #capcha gg
    'captcha',
    'import_export'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'users.User'
ROOT_URLCONF = 'insecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'insecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'rootapp123',
        'HOST': 'db',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = False


LANGUAGES = (
    ('vi', _('Viet Nam')),
    ('en', _('English')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# STATIC_ROOT =  '/static/'
CORS_ORIGIN_ALLOW_ALL = True

# Setting cache framework
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/0',
        'KEY_PREFIX': 'bihama',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"
# Celery task queue configs

CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_BACKEND_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_BEAT_SCHEDULE = {
    # 'thong_tin_don_hang_chua_gui': {
    #     'task': 'apps.personalhealth.tasks.thong_tin_don_hang_chua_gui',
    #     'schedule': crontab('*/60')
    # },
    # 'filter_dh_tndsoto_chuagui_mana': {
    #     'task': 'apps.tndsoto.tasks.filter_dh_tndsoto_chuagui_mana',
    #     'schedule': crontab('*/60')
    # },
    # 'filter_dh_tsdsxemay_chuagui_mana': {
    #     'task': 'apps.tndsxemay.tasks.filter_dh_tsdsxemay_chuagui_mana',
    #     'schedule': crontab('*/60')
    # },
    # 'filter_dhhome_chuagui_mana': {
    #     'task': 'apps.homeinsurance.tasks.filter_dhhome_chuagui_mana',
    #     'schedule': crontab('*/60')
    # }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# rest_framework set up
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'apps.users.auth.BearerAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'EXCEPTION_HANDLER': 'apps.core.views.exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10,
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': None,
    },
    'default': {
        'toolbar': 'full',
        'height': 700,
        'width': 1000,
    },
}

DATA_UPLOAD_MAX_MEMORY_SIZE = 25242880
FILE_UPLOAD_MAX_MEMORY_SIZE = 25242880

OTP_API_KEY = "BC07A49D336EF3B2189F6D9FAE5BA2"
OTP_SECRETKEY = "03C17747EF9CEE01B5CB6DDA018E71"

VNPAY_RETURN_URL = 'http://bihama.com/payment_return'  # get from config
VNPAY_PAYMENT_URL = 'http://sandbox.vnpayment.vn/paymentv2/vpcpay.html'  # get from config
VNPAY_API_URL = 'http://sandbox.vnpayment.vn/merchant_webapi/merchant.html'
VNPAY_TMN_CODE = 'BESTL001'  # Website ID in VNPAY System, get from config
VNPAY_HASH_SECRET_KEY = 'OCTAFKFPUJBUMASQLUWDIJPGHUTJRMDC'  # Secret key for create checksum,get from config

# PORTAL_URL = "http://portal.bihama.vn/"
# MANAGER_URL = "https://manager.bihama.vn/"
# BIHAMA_URL = "https://bihama.vn/"

BIHAMA_REGISTER_URL="https://0.0.0.0:8000"
URL_RIGISTER_CTV='https://0.0.0.0:8000'

TAICHINH_URL = "https://taichinh.bihama.vn/"
YTE_URL = "https://bacsi.bihama.vn/"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'dangkybihama@gmail.com'
EMAIL_HOST_PASSWORD = 'bihama#8800'

#key_capcha
RECAPTCHA_PUBLIC_KEY='6LeT46QZAAAAALIxvOE1wGEqU5c6qzEZVrUOnpXG'
RECAPTCHA_PRIVATE_KEY='6LeT46QZAAAAALvfIBMZDceGQ8-E6ci72R8HT-eI'

SECURITY_KEY_CTV_MANA = "46ae0833741f2372a02d35a8f22b32e9ca2274ab"
SECURITY_KEY_MANA_SAN = "cae831ce33cc03e1ff3e2823fe1346921f6704c6"
SECURITY_KEY_CTV_SAN = "547d2867695091b7b8c66f54320327bc5176f69b"

SECURITY_KEY_YTE_SAN = "b7e0df5373929ae78f81e6834a463067aabba433"
SECURITY_KEY_TAICHINH_SAN = "bb844013ba515a06b34dedeece3dd8d1015bd22d"
SECURITY_KEY_TAICHINH_YTE = "f2b6e88a8747d442303f5980ba84a9c85cc46415"

SECURITY_KEY_YTE_MANA = "e6e5a261ab859ac24a35c58d14062f6ab6865777"
SECURITY_KEY_TAICHINH_MANA = "0807847106e3dbde54fddf845f0cf24a23c11d06"

SECURITY_KEY_YTE_CTV = "738dbec8a330dd2394acc4d88fc508c81ad8def0"
SECURITY_KEY_TAICHINH_CTV = "2a738f332906cc338a3e803c14ac0765d2616c3c"