# Generated by Django 2.2.2 on 2021-02-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDuocBaoHiemTam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('fullname', models.CharField(default=None, max_length=200, null=True)),
                ('birth_day', models.IntegerField(default=0)),
                ('birth_month', models.IntegerField(default=0)),
                ('birth_year', models.IntegerField(default=0)),
                ('gioi_tinh', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=255, null=True)),
                ('dia_chi_tinh_thanh_pho', models.CharField(max_length=255, null=True)),
                ('dia_chi_quan_huyen', models.CharField(max_length=255, null=True)),
                ('dia_chi_chi_tiet', models.CharField(max_length=255, null=True)),
                ('so_cmnd', models.CharField(max_length=255, null=True)),
                ('images_cmt_mattruoc', models.TextField(default=None, null=True)),
                ('images_cmt_matsau', models.TextField(default=None, null=True)),
                ('cmt_ngay_cap', models.DateField(null=True)),
                ('cmt_noi_cap', models.CharField(max_length=255, null=True)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('cau_hoi_suc_khoe_1', models.IntegerField(default=0)),
                ('cau_hoi_suc_khoe_2', models.IntegerField(default=0)),
                ('chi_tiet_benh_tat', models.TextField(null=True)),
                ('relationship', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoimuabaohiemtam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalhealth', to='core.NguoiMuaBaoHiemTam')),
            ],
            options={
                'verbose_name': 'Người được bảo hiểm tạm',
                'verbose_name_plural': 'Người được bảo hiểm tạm',
            },
        ),
        migrations.CreateModel(
            name='NguoiDuocBaoHiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_hang_bihama', models.CharField(max_length=255)),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('fullname', models.CharField(default=None, max_length=200, null=True)),
                ('birth_day', models.IntegerField(default=0)),
                ('birth_month', models.IntegerField(default=0)),
                ('birth_year', models.IntegerField(default=0)),
                ('gioi_tinh', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=255, null=True)),
                ('dia_chi_tinh_thanh_pho', models.CharField(max_length=255, null=True)),
                ('dia_chi_quan_huyen', models.CharField(max_length=255, null=True)),
                ('dia_chi_chi_tiet', models.CharField(max_length=255, null=True)),
                ('so_cmnd', models.CharField(max_length=255, null=True)),
                ('images_cmt_mattruoc', models.TextField(default=None, null=True)),
                ('images_cmt_matsau', models.TextField(default=None, null=True)),
                ('cmt_ngay_cap', models.DateField(null=True)),
                ('cmt_noi_cap', models.CharField(max_length=255, null=True)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('cau_hoi_suc_khoe_1', models.IntegerField(default=0)),
                ('cau_hoi_suc_khoe_2', models.IntegerField(default=0)),
                ('chi_tiet_benh_tat', models.TextField(blank=True, null=True)),
                ('relationship', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoimuabaohiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalhealth', to='core.NguoiMuaBaoHiem')),
            ],
            options={
                'verbose_name': 'Người được bảo hiểm',
                'verbose_name_plural': 'Người được bảo hiểm',
            },
        ),
        migrations.CreateModel(
            name='GoiSanPhamPhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_hinh_bao_hiem', models.CharField(max_length=255, null=True)),
                ('id_loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('gioi_tinh', models.IntegerField(default=0)),
                ('tuoi', models.IntegerField(default=0)),
                ('ten_goi_san_pham_chinh', models.CharField(max_length=255, null=True)),
                ('id_goi_san_pham_chinh', models.IntegerField(default=0)),
                ('ten_goi_san_pham_phu', models.CharField(max_length=255, null=True)),
                ('id_goi_san_pham_phu', models.IntegerField(default=0)),
                ('so_phi_phu', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalhealth2', to='core.Company')),
            ],
            options={
                'verbose_name': 'Gói sản phẩm phụ',
                'verbose_name_plural': 'Gói sản phẩm phụ',
            },
        ),
        migrations.CreateModel(
            name='GoiSanPhamChinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_hinh_bao_hiem', models.CharField(max_length=255, null=True)),
                ('id_loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('gioi_tinh', models.IntegerField(default=0)),
                ('tuoi', models.IntegerField(default=0)),
                ('ten_goi_san_pham_chinh', models.CharField(max_length=255, null=True)),
                ('id_goi_san_pham_chinh', models.IntegerField(default=0)),
                ('so_phi_chinh', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalhealth1', to='core.Company')),
            ],
            options={
                'verbose_name': 'Gói sản phẩm chính',
                'verbose_name_plural': 'Gói sản phẩm chính',
            },
        ),
    ]
