# Generated by Django 2.2.2 on 2021-02-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDuocBaoHiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_hang_bihama', models.CharField(max_length=255)),
                ('loai_nha', models.IntegerField(default=0)),
                ('muc_dich_nha', models.IntegerField(default=0)),
                ('tuoi_tho_ngoi_nha', models.IntegerField(default=0)),
                ('dia_chi_tinh_thanh_pho', models.CharField(max_length=255, null=True)),
                ('dia_chi_quan_huyen', models.CharField(max_length=255, null=True)),
                ('dia_chi_chi_tiet', models.CharField(max_length=255, null=True)),
                ('gia_tri_can_nha', models.BigIntegerField(default=0)),
                ('gia_tri_tai_san_ben_trong', models.BigIntegerField(default=0)),
                ('so_tien_bh', models.BigIntegerField(default=0)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('relationship', models.IntegerField(default=0)),
                ('is_fire', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoimuabaohiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_insurance2', to='core.NguoiMuaBaoHiem')),
            ],
            options={
                'verbose_name': 'Người được bảo hiểm',
                'verbose_name_plural': 'Người được bảo hiểm',
            },
        ),
        migrations.CreateModel(
            name='NguoiThuHuong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default=None, max_length=200, null=True)),
                ('birth_day', models.IntegerField(default=0)),
                ('birth_month', models.IntegerField(default=0)),
                ('birth_year', models.IntegerField(default=0)),
                ('gioi_tinh', models.IntegerField(default=0)),
                ('so_cmnd', models.CharField(max_length=255, null=True)),
                ('nguoiduocbaohiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_insurance3', to='homeinsurance.NguoiDuocBaoHiem')),
            ],
            options={
                'verbose_name': 'Người thụ hưởng',
                'verbose_name_plural': 'Người thụ hưởng',
            },
        ),
        migrations.CreateModel(
            name='NguoiDuocBaoHiemTam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_nha', models.IntegerField(default=0)),
                ('muc_dich_nha', models.IntegerField(default=0)),
                ('tuoi_tho_ngoi_nha', models.IntegerField(default=0)),
                ('dia_chi_tinh_thanh_pho', models.CharField(max_length=255, null=True)),
                ('dia_chi_quan_huyen', models.CharField(max_length=255, null=True)),
                ('dia_chi_chi_tiet', models.CharField(max_length=255, null=True)),
                ('gia_tri_can_nha', models.BigIntegerField(default=0)),
                ('gia_tri_tai_san_ben_trong', models.BigIntegerField(default=0)),
                ('so_tien_bh', models.BigIntegerField(default=0)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('relationship', models.IntegerField(default=0)),
                ('is_fire', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoimuabaohiemtam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_insurance1', to='core.NguoiMuaBaoHiemTam')),
            ],
            options={
                'verbose_name': 'Người được bảo hiểm tạm',
                'verbose_name_plural': 'Người được bảo hiểm tạm',
            },
        ),
        migrations.CreateModel(
            name='GoiSanPhamPhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_hinh_bao_hiem', models.CharField(max_length=255, null=True)),
                ('id_loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('ten_goi_san_pham_chinh', models.CharField(max_length=255, null=True)),
                ('id_goi_san_pham_chinh', models.IntegerField(default=0)),
                ('ten_goi_san_pham_phu', models.CharField(max_length=255, null=True)),
                ('id_goi_san_pham_phu', models.IntegerField(default=0)),
                ('so_phi_phu', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_insurance5', to='core.Company')),
            ],
            options={
                'verbose_name': 'Gói sản phẩm phụ',
                'verbose_name_plural': 'Gói sản phẩm phụ',
            },
        ),
        migrations.CreateModel(
            name='GoiSanPhamChinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_hinh_bao_hiem', models.CharField(max_length=255, null=True)),
                ('id_loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('ten_goi_san_pham_chinh', models.CharField(max_length=255, null=True)),
                ('id_goi_san_pham_chinh', models.IntegerField(default=0)),
                ('so_phi_chinh', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_insurance4', to='core.Company')),
            ],
            options={
                'verbose_name': 'Gói sản phẩm chính',
                'verbose_name_plural': 'Gói sản phẩm chính',
            },
        ),
    ]
