# Generated by Django 2.2.2 on 2021-02-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDuocBaoHiemTam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien_so_xe', models.CharField(max_length=255, null=True)),
                ('loai_nguoi_mua', models.IntegerField(default=0)),
                ('muc_dich_su_dung', models.IntegerField(default=0)),
                ('trong_tai', models.IntegerField(default=0)),
                ('so_tien_bao_hiem_tnds_tu_nguyen', models.IntegerField(default=0)),
                ('images_dangky_mattruoc', models.TextField(default=None, null=True)),
                ('images_dangky_matsau', models.TextField(default=None, null=True)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoimuabaohiemtam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tndsoto', to='core.NguoiMuaBaoHiemTam')),
            ],
            options={
                'verbose_name': 'Người được bảo hiểm tạm',
                'verbose_name_plural': 'Người được bảo hiểm tạm',
            },
        ),
        migrations.CreateModel(
            name='NguoiDuocBaoHiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_hang_bihama', models.CharField(max_length=255)),
                ('bien_so_xe', models.CharField(max_length=255, null=True)),
                ('loai_nguoi_mua', models.IntegerField(default=0)),
                ('muc_dich_su_dung', models.IntegerField(default=0)),
                ('trong_tai', models.IntegerField(default=0)),
                ('so_tien_bao_hiem_tnds_tu_nguyen', models.IntegerField(default=0)),
                ('images_dangky_mattruoc', models.TextField(default=None, null=True)),
                ('images_dangky_matsau', models.TextField(default=None, null=True)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('nguoimuabaohiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tndsoto', to='core.NguoiMuaBaoHiem')),
            ],
            options={
                'verbose_name': 'Người được bảo hiểm',
                'verbose_name_plural': 'Người được bảo hiểm',
            },
        ),
        migrations.CreateModel(
            name='GoiSanPhamPhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_hinh_bao_hiem', models.CharField(max_length=255, null=True)),
                ('id_loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('ten_goi_san_pham_phu', models.CharField(max_length=255, null=True)),
                ('id_goi_san_pham_phu', models.IntegerField(default=0)),
                ('so_phi_phu', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tndsoto2', to='core.Company')),
            ],
            options={
                'verbose_name': 'Gói sản phẩm phụ',
                'verbose_name_plural': 'Gói sản phẩm phụ',
            },
        ),
        migrations.CreateModel(
            name='GoiSanPhamChinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai_hinh_bao_hiem', models.CharField(max_length=255, null=True)),
                ('id_loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('ten_trong_tai', models.CharField(max_length=255, null=True)),
                ('id_trong_tai', models.IntegerField(default=0)),
                ('so_phi_chinh', models.FloatField(default=0.0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tndsoto1', to='core.Company')),
            ],
            options={
                'verbose_name': 'Gói sản phẩm chính',
                'verbose_name_plural': 'Gói sản phẩm chính',
            },
        ),
    ]
