# Generated by Django 2.2.2 on 2021-02-23 13:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KienthucCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category Kiến thức',
                'verbose_name_plural': 'Category Kiến thức',
            },
        ),
        migrations.CreateModel(
            name='KienThucModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('link_video', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('images', models.TextField(default=None, null=True)),
                ('status', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kienthuc.KienthucCategory')),
            ],
            options={
                'verbose_name': 'Kiến thức',
                'verbose_name_plural': 'Kiến thức',
            },
        ),
    ]
