# Generated by Django 2.2.2 on 2021-02-23 13:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietCongViec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chitiet', models.CharField(default=None, max_length=200, null=True)),
                ('code_chitiet', models.IntegerField(default=0)),
                ('code_linhvuc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chi tiết công việc',
                'verbose_name_plural': 'Chi tiết công việc',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField(blank=True, null=True)),
                ('ten_cong_ty', models.CharField(max_length=255, null=True)),
                ('id_ten_cong_ty', models.IntegerField(default=0)),
                ('bai_gioi_thieu_cong_ty', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('nam_thanh_lap', models.CharField(default=None, max_length=200, null=True)),
                ('bien_thanh_toan', models.FloatField(default=0.0)),
                ('so_chi_nhanh', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_code', models.IntegerField(default=0)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Quận huyện ',
                'verbose_name_plural': 'Quận huyện',
            },
        ),
        migrations.CreateModel(
            name='GoogleVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('expires_in', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('scope', models.URLField(blank=True, null=True)),
                ('token_type', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'AI GoogleCloud',
                'verbose_name_plural': 'AI GoogleCloud',
            },
        ),
        migrations.CreateModel(
            name='LinhVuNgheNghiep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linhvuc', models.CharField(default=None, max_length=200, null=True)),
                ('code_linhvuc', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lĩnh vực nghề nghiệp',
                'verbose_name_plural': 'Lĩnh vực nghề nghiệp',
            },
        ),
        migrations.CreateModel(
            name='NguoiMuaBaoHiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('fullname', models.CharField(default=None, max_length=200, null=True)),
                ('birth_day', models.IntegerField(default=0)),
                ('birth_month', models.IntegerField(default=0)),
                ('birth_year', models.IntegerField(default=0)),
                ('gioi_tinh', models.IntegerField(default=0)),
                ('email', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_tinh_thanh_pho', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_quan_huyen', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_chi_tiet', models.CharField(default=None, max_length=200, null=True)),
                ('so_cmnd', models.CharField(default=None, max_length=200, null=True)),
                ('images_cmt_mattruoc', models.TextField(default=None, null=True)),
                ('images_cmt_matsau', models.TextField(default=None, null=True)),
                ('cmt_ngay_cap', models.DateField(null=True)),
                ('cmt_noi_cap', models.CharField(default=None, max_length=200, null=True)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('ho_ten_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('email_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('so_dien_thoai_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_tinh_thanh_pho_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_quan_huyen_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_chi_tiet_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('status_marriage', models.IntegerField(default=0)),
                ('job', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('nationality', models.IntegerField(default=0)),
                ('nationality_paper', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Người mua bảo hiểm',
                'verbose_name_plural': 'Người mua bảo hiểm',
            },
        ),
        migrations.CreateModel(
            name='NguoiMuaBaoHiemTam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=200, null=True)),
                ('fullname', models.CharField(default=None, max_length=200, null=True)),
                ('birth_day', models.IntegerField(default=0)),
                ('birth_month', models.IntegerField(default=0)),
                ('birth_year', models.IntegerField(default=0)),
                ('gioi_tinh', models.IntegerField(default=0)),
                ('email', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_tinh_thanh_pho', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_quan_huyen', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_chi_tiet', models.CharField(default=None, max_length=200, null=True)),
                ('so_cmnd', models.CharField(default=None, max_length=200, null=True)),
                ('images_cmt_mattruoc', models.TextField(default=None, null=True)),
                ('images_cmt_matsau', models.TextField(default=None, null=True)),
                ('cmt_ngay_cap', models.DateField(null=True)),
                ('cmt_noi_cap', models.CharField(default=None, max_length=200, null=True)),
                ('ngay_hieu_luc', models.DateTimeField(null=True)),
                ('ngay_ket_thuc', models.DateTimeField(null=True)),
                ('ho_ten_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('email_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('so_dien_thoai_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_tinh_thanh_pho_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_quan_huyen_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('dia_chi_chi_tiet_nhan', models.CharField(default=None, max_length=200, null=True)),
                ('status_marriage', models.IntegerField(default=0)),
                ('job', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('nationality', models.IntegerField(default=0)),
                ('nationality_paper', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Người mua bảo hiểm tạm',
                'verbose_name_plural': 'Người mua bảo hiểm tạm',
            },
        ),
        migrations.CreateModel(
            name='NoiDungNgheNghiep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noidungcongviec', models.TextField(default=None, null=True)),
                ('code_chitiet', models.IntegerField(default=0)),
                ('capnghenghiep', models.IntegerField(default=0)),
                ('hanchetichluy', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nội dung công việc',
                'verbose_name_plural': 'Nội dung công việc',
            },
        ),
        migrations.CreateModel(
            name='Provincial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField(default=0)),
                ('group', models.IntegerField(default=0)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tỉnh thành phố ',
                'verbose_name_plural': 'Tỉnh thành phố',
            },
        ),
    ]
