# Generated by Django 2.2.2 on 2021-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot1DauTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
                ('ma_don_hang_bihama', models.CharField(max_length=255, unique=True)),
                ('cong_ty', models.IntegerField(default=0)),
                ('loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('goi_san_pham_chinh', models.IntegerField(default=0)),
                ('goi_san_pham_phu', models.TextField(default=None, null=True)),
                ('so_phi_chinh', models.BigIntegerField(default=0)),
                ('tong_so_phi_phu', models.BigIntegerField(default=0)),
                ('tong_phi_thanh_toan', models.BigIntegerField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('tuoi', models.IntegerField(default=0)),
                ('thu_nhap_hang_nam', models.IntegerField(default=0)),
                ('khi_dau_tu_ban_quan_tam_gi_nhat', models.IntegerField(default=0)),
                ('co_hoi_nhan_thuong_chuong_trinh_truyen_hinh', models.IntegerField(default=0)),
                ('y_tuong_rui_ro_trong_dau_tu', models.IntegerField(default=0)),
                ('du_bao_gia_vang', models.IntegerField(default=0)),
                ('tim_quy_dau_tu', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Robot1 đầu tư',
                'verbose_name_plural': 'Robot1 đầu tư',
            },
        ),
        migrations.CreateModel(
            name='RobotChung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
                ('ma_don_hang_bihama', models.CharField(max_length=255, unique=True)),
                ('cong_ty', models.IntegerField(default=0)),
                ('loai_hinh_bao_hiem', models.IntegerField(default=0)),
                ('goi_san_pham_chinh', models.IntegerField(default=0)),
                ('goi_san_pham_phu', models.TextField(default=None, null=True)),
                ('so_phi_chinh', models.BigIntegerField(default=0)),
                ('tong_so_phi_phu', models.BigIntegerField(default=0)),
                ('tong_phi_thanh_toan', models.BigIntegerField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('tuoi', models.IntegerField(default=0)),
                ('tham_gia_bao_hiem_xa_hoi', models.IntegerField(default=0)),
                ('tham_gia_bao_hiem_y_te', models.IntegerField(default=0)),
                ('thu_nhap_hang_nam', models.IntegerField(default=0)),
                ('muc_dich_tham_gia_bao_hiem', models.IntegerField(default=0)),
                ('tinh_trang_hon_nhan', models.IntegerField(default=0)),
                ('ban_dang_la', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Robot chung',
                'verbose_name_plural': 'Robot chung',
            },
        ),
    ]
