# Generated by Django 2.2.2 on 2021-02-23 13:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurancecompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cpn', models.IntegerField(default=0)),
                ('name_cpn', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, null=True)),
                ('sub_title', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('title', models.CharField(max_length=200, null=True)),
                ('link_cpn', models.CharField(max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('tac_gia', models.CharField(max_length=200)),
                ('seo_key_word', models.CharField(default=None, max_length=200, null=True)),
                ('images', models.TextField(default=None, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Công ty bảo hiểm',
                'verbose_name_plural': 'Công ty bảo hiểm',
            },
        ),
    ]
